name: Benchmarks
on:
  pull_request_target:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  pull-requests: write
jobs:
  benchmark:
    uses: "SciML/.github/.github/workflows/benchmark.yml@v1"
    with:
      julia-version: "1"
    secrets: "inherit"
