name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'   # LTS
          - '1'      # latest stable
        os:
          - ubuntu-latest
    uses: "SciML/.github/.github/workflows/tests.yml@v1"
    with:
      julia-version: "${{ matrix.version }}"
      os: "${{ matrix.os }}"
    secrets: "inherit"
  downgrade:
    name: Downgrade compat - Julia ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
    uses: "SciML/.github/.github/workflows/downgrade.yml@v1"
    with:
      julia-version: "${{ matrix.version }}"
      skip: "LinearAlgebra,Test,Aqua,SafeTestsets"
    secrets: "inherit"
